name: cla-check
on:
  pull_request:
  merge_group:

jobs:
  cla-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
        # This prevents the action from running on a merge group, where it fails.
        if: ${{ github.event_name != "merge_group" }}
